# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
import numpy as np
a = np.random.randint(10,24,24)
print(a)

[18 10 14 22 16 22 17 12 12 10 12 12 20 23 18 16 15 14 20 22 13 12 11 14]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
b = np.arange(1,50,2)
print(b)
print("length:", len(b))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
length: 25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
c = np.linspace(4,7,27)
print(c)

[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
d = np.random.randn(5,4)
print("Original matrix: \n", d)
print("Rounded off matrix: \n", np.round(d,2))

Original matrix: 
 [[-0.07793136  0.11295672 -0.57979465 -0.02562164]
 [ 0.31082617  0.40973652  1.76740123 -0.51114303]
 [ 0.24987857 -0.33270095 -0.27324173  0.75688836]
 [ 0.36181435 -0.23414867  1.24044177  0.51179854]
 [-2.43847417 -0.14748417 -1.07822843 -1.4312917 ]]
Rounded off matrix: 
 [[-0.08  0.11 -0.58 -0.03]
 [ 0.31  0.41  1.77 -0.51]
 [ 0.25 -0.33 -0.27  0.76]
 [ 0.36 -0.23  1.24  0.51]
 [-2.44 -0.15 -1.08 -1.43]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
e = np.random.randint(5,15,(5,5))
print("matrix: \n",e)

matrix: 
 [[11  6 12  8  6]
 [ 7 13 11 11 13]
 [ 7 14  7  8  9]
 [ 5  9 10  7  5]
 [11  5 11  5 13]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
f = np.zeros(7, dtype=int)
print("1d array:",f)

1d array: [0 0 0 0 0 0 0]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
g = np.ones((2,3), dtype=float)
print("2d array: \n",g)

2d array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
h = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print("matrix value: \n", h)
print("matrix shape:", h.shape)
print("matrix type:", type(h))
print("matrix dtype:", h.dtype)

matrix value: 
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
matrix shape: (5, 5)
matrix type: <class 'numpy.ndarray'>
matrix dtype: int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:
h = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print("matrix: \n", h)
hnew = h.flatten()
mv = hnew[int(len(hnew)/2)]
print("center value of the matrix:", mv)

matrix: 
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
center value of the matrix: 3


#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
print(h)
print("row 3:", h[[2], :])

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
row 3: [[ 5  7  3 76  3]]


#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
print(h)
print("column 4: \n", h[:,[3]])

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
column 4: 
 [[34]
 [65]
 [76]
 [54]
 [ 5]]


#### 12. Print the 4 corner pixels of the matrix

In [12]:
print("original matrix is: \n", h)
m,n = h.shape
print("corner pixels: \n", h[::m-1, ::n-1])

original matrix is: 
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
corner pixels: 
 [[ 9 45]
 [23  8]]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
m1 = h[:2, 2:4]
print("m1: \n",m1)

m2 = h[3:, :2]
print("m2: \n",m2)

m3 = h[2:, 2:]
print("m3: \n",m3)

m1: 
 [[50 34]
 [34 65]]
m2: 
 [[ 7  8]
 [23 12]]
m3: 
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
print("m1 reshaped:", m1.flatten())
print("m2 reshaped:", m2.flatten())
print("m3 reshaped:", m3.flatten())

m1 reshaped: [50 34 34 65]
m2 reshaped: [ 7  8 23 12]
m3 reshaped: [ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
vert = np.vstack((m1,m2))
horz = np.hstack((m1,m2))
print("vertical concatenated matrix: \n", vert)
print("horizontal concatenated matrix: \n", horz)

vertical concatenated matrix: 
 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
horizontal concatenated matrix: 
 [[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [16]:
print("matrix addition: \n", np.add(m1,m2))
print("matrix subtraction: \n", np.subtract(m1,m2))
print("matrix multiplication: \n", np.matmul(m1,m2))
print("matrix division: \n", np.divide(m1,m2))

matrix addition: 
 [[57 42]
 [57 77]]
matrix subtraction: 
 [[43 26]
 [11 53]]
matrix multiplication: 
 [[1132  808]
 [1733 1052]]
matrix division: 
 [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [17]:
print("m1: \n", m1)
print("m3: \n", m3)
new = np.delete(m3,0,0)
new = np.delete(new,2,1)
print("new m3: \n", new)
print("m1+m3 gives: \n", m1+new)

m1: 
 [[50 34]
 [34 65]]
m3: 
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]
new m3: 
 [[ 6 54]
 [ 8  5]]
m1+m3 gives: 
 [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [18]:
me1 = m1[:,0].mean()
me2 = m1[:,1].mean()
newme = np.array([[me1,me2]])
m4 = np.concatenate((m1,newme),axis=0)
print("m4: \n", m4)

m4: 
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [19]:
print("multiplied matrix: \n", np.matmul(m3,m4))

multiplied matrix: 
 [[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [20]:
r1 = np.mean(h, axis=1)[0]
r2 = np.mean(h, axis=1)[1]
r3 = np.mean(h, axis=1)[2]
r4 = np.mean(h, axis=1)[3]
r5 = np.mean(h, axis=1)[4]
mean = np.vstack([r1,r2,r3,r4,r5])
print("mean: \n", mean)
v1 = np.var(h, axis=1)[0]
v2 = np.var(h, axis=1)[1]
v3 = np.var(h, axis=1)[2]
v4 = np.var(h, axis=1)[3]
v5 = np.var(h, axis=1)[4]
vari = np.vstack([v1,v2,v3,v4,v5])
print("variance: \n", vari)
sd1 = np.std(h, axis=1)[0]
sd2 = np.std(h, axis=1)[1]
sd3 = np.std(h, axis=1)[2]
sd4 = np.std(h, axis=1)[3]
sd5 = np.std(h, axis=1)[4]
sd = np.vstack([sd1,sd2,sd3,sd4,sd5])
print("standard deviation: \n", sd)

print("minimum mean:" ,np.min(mean))
print("maximum mean:" ,np.max(mean))
print("minimum variance:" ,np.min(vari))
print("maximum variance:" ,np.max(vari))
print("minimum standard deviation:" ,np.min(sd))
print("maximum standard deviation:" ,np.max(sd))

mean: 
 [[32.6]
 [27.6]
 [18.8]
 [16.2]
 [11.2]]
variance: 
 [[214.64]
 [548.24]
 [820.16]
 [357.76]
 [ 39.76]]
standard deviation: 
 [[14.65059726]
 [23.41452541]
 [28.63843571]
 [18.91454467]
 [ 6.30555311]]
minimum mean: 11.2
maximum mean: 32.6
minimum variance: 39.760000000000005
maximum variance: 820.1600000000001
minimum standard deviation: 6.305553108173779
maximum standard deviation: 28.63843571147


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [21]:
runs = np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls = np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])

msd = np.average(runs, axis=1)[0]
koh = np.average(runs, axis=1)[1]
roh = np.average(runs, axis=1)[2]
rah = np.average(runs, axis=1)[3]
dhw = np.average(runs, axis=1)[4]
avg = np.vstack([msd,koh,roh,rah,dhw])
print("average for each player: \n", avg)
#avgsort = np.sort(avg, axis=0)
#print("asc: \n", avgsort)
print("descending order for player's average: \n", np.sort(avg, axis=0)[::-1])

mrun = np.sum(runs, axis=1)[0]
mball = np.sum(balls, axis=1)[0]
krun = np.sum(runs, axis=1)[1]
kball = np.sum(balls, axis=1)[1]
rorun = np.sum(runs, axis=1)[2]
roball = np.sum(balls, axis=1)[2]
rarun = np.sum(runs, axis=1)[3]
raball = np.sum(balls, axis=1)[3]
drun = np.sum(runs, axis=1)[4]
dball = np.sum(balls, axis=1)[4]

totrun = np.vstack([mrun,krun,rorun,rarun,drun])
totball = np.vstack([mball,kball,roball,raball,dball])
strikerate = np.divide(totrun,totball)*100
print("strike rate for each player: \n", strikerate)
#srsort = np.sort(strikerate, axis=0)
#print("asc: \n", srsort)
print("descending order for player's strikerate: \n", np.sort(strikerate, axis=0)[::-1])

average for each player: 
 [[47.25]
 [53.5 ]
 [51.5 ]
 [29.  ]
 [13.25]]
descending order for player's average: 
 [[53.5 ]
 [51.5 ]
 [47.25]
 [29.  ]
 [13.25]]
strike rate for each player: 
 [[ 98.4375    ]
 [101.42180095]
 [ 94.93087558]
 [161.11111111]
 [ 49.53271028]]
descending order for player's strikerate: 
 [[161.11111111]
 [101.42180095]
 [ 98.4375    ]
 [ 94.93087558]
 [ 49.53271028]]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [22]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
passed = (marks[:]>=50).sum()
failed = (marks[:]<50).sum()
print("number of students passed:", passed)
print("number of students failed:", failed)

number of students passed: 7
number of students failed: 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [24]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
print("initial student marks:",marks)
print("students passed:",(marks>=50).sum(), ", students failed:",((marks)<50).sum())
tot = len(marks)
passrate = np.divide(passed,tot)*100
print("initial class pass percent:", passrate)

for i in range(0,tot):
    if(((marks[i]>45)&(marks[i]<49))|(marks[i]>80)):
        marks[i] = marks[i] + 5
        if(marks[i]>=100):
            marks[i]=100

print("new marks obtained after mercy marks:",marks)
newpassval = (marks[:]>=50).sum()
newpassrate = np.divide(newpassval,tot)*100
print("students passed:",(marks>=50).sum(), ", students failed:",((marks)<50).sum())
print("new class pass percent:",newpassrate)
print("increase in class percent:",newpassrate-passrate)

initial student marks: [65 84 47 56 89 98 48 77 80 39]
students passed: 7 , students failed: 3
initial class pass percent: 70.0
new marks obtained after mercy marks: [ 65  89  52  56  94 100  53  77  80  39]
students passed: 9 , students failed: 1
new class pass percent: 90.0
increase in class percent: 20.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [25]:
import time
def lis():
    ax = list(range(1,60000))
    by = list(range(1,60000))
    fin = []
    for i in range(len(ax)):
        fin.append(((ax[i]**2)+8)/by[i])

def nump():
    ax2 = np.array(range(1,60000))
    by2 = np.array(range(1,60000))
    fin = ((ax2**2)+8)/by2
st_time = time.time()
%time lis()
end_time = time.time()
print("The time taken to perform the operation by list is:", end_time-st_time)
st2_time = time.time()
%time nump()
end2_time = time.time()
print("The time taken to perform the operation by numpy is:", end2_time-st2_time)

Wall time: 96 ms
The time taken to perform the operation by list is: 0.11408424377441406
Wall time: 93.6 ms
The time taken to perform the operation by numpy is: 0.09363007545471191


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [26]:
#https://github.com/ashika7